from pydantic import BaseModel, Field
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query # Add Query to imports
from typing import Optional
from fastapi.middleware.cors import CORSMiddleware
import re
import ast
import uuid
# Import your LangChain agent and message models
from agent.ticket_agent import create_isp_agent
from langchain_core.messages import HumanMessage, AIMessage

# Load environment variables
load_dotenv()

app = FastAPI(
    title="ISP Agentic Ticket System API",
    description="REST API to interact with the autonomous ISP ticketing agent",
    version="1.0.0"
)

# 2. Configure CORS to allow your frontend connection
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allows all origins (good for local testing)
    allow_credentials=True,
    allow_methods=["*"], # Allows GET, POST, etc.
    allow_headers=["*"],
)


# Initialize the agent executor globally once at startup
agent_executor = create_isp_agent()

# Simple in-memory session storage: { session_id: [list_of_messages] }
# Note: For production use, replace this with a Redis-backed history store.
session_storage = {}


# --- Request & Response Schemas ---

class ChatRequest(BaseModel):
    message: str = Field(..., description="The textual input message from the user")
    session_id: Optional[str] = Field(
        None,
        description="The unique session ID to track conversation state. Leave empty to start a new session."
    )


class ChatResponse(BaseModel):
    session_id: str = Field(..., description="The active session ID for continuing the thread")
    response: str = Field(..., description="The plain-text answer generated by the agent")


# --- Helper Function for Double Sanitization ---

# --- ULTIMATE SANITIZATION FUNCTION ---
def force_clean_agent_output(output: str) -> str:
    """
    Guarantees that raw dictionary tokens, list syntax, and signature blocks
    are completely scrubbed, leaving only clear human text.
    """
    output_str = str(output).strip()

    # Check if the output contains the signature token leakage
    if "[{'type':" in output_str or "{'signature':" in output_str:
        try:
            # Attempt 1: Safely evaluate string representation of list of dicts
            # We match the array boundaries using a regex sweep
            match = re.search(r'\[\s*\{.*\}\s*\]', output_str, re.DOTALL)
            if match:
                parsed_list = ast.literal_eval(match.group(0))
                clean_text = "".join([item.get('text', '') for item in parsed_list if isinstance(item, dict)])
                if clean_text:
                    return clean_text.strip()
        except Exception:
            pass

        # Attempt 2: Fallback RegExp cleanup to strip any bracketed junk manually
        # Removes anything inside the inner structural metadata container
        output_str = re.sub(r"\[?\{'type'.*?'index':\s*\d+\},?\s*", "", output_str, flags=re.DOTALL)
        output_str = output_str.replace("']", "").replace("['", "").strip()

    return output_str
# --- API Routes ---


@app.get("/api/chat")
async def chat_endpoint(
        message: str = Query(..., description="The textual input message from the user"),
        session_id: Optional[str] = Query(
            None,
            description="The unique session ID to track conversation state. Leave empty to start a new session."
        )
):
    try:
        # 1. Resolve or generate session_id
        current_session_id = session_id or str(uuid.uuid4())

        # 2. Retrieve history for this session, or initialize a new one
        if current_session_id not in session_storage:
            session_storage[current_session_id] = []

        chat_history = session_storage[current_session_id]

        # 3. Invoke the LangChain Agent Executor
        result = agent_executor.invoke({
            "input": message,
            "chat_history": chat_history
        })

        raw_output = result.get('output', '')
        clean_output = force_clean_agent_output(raw_output)

        # 4. Save the current turn into memory for context preservation
        from langchain_core.messages import HumanMessage, AIMessage
        chat_history.append(HumanMessage(content=message))
        chat_history.append(AIMessage(content=clean_output))

        # 5. Return payload directly as a dictionary
        return {
            "session_id": current_session_id,
            "response": clean_output
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent Execution Error: {str(e)}")


if __name__ == "__main__":
    import uvicorn

    # Spin up the Uvicorn dev engine locally on port 8000
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)